name: CI

on:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/demo_app
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  ACCESS_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Extract version
      id: extract_version
      run: echo "::set-output name=VERSION::$(echo ${GITHUB_REF#refs/tags/})"
    
    - name: Checkout code
      uses: actions/checkout@v2
      with: 
        ref: main
        token: ${{ secrets.REPOSITORY_TOKEN }}
      
    - name: Set up JDK 1.11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ steps.extract_version.outputs.VERSION }}

    - name: Update Kubernetes deployment
      run: |
        find ./deploy -type f -name "*.yaml" -exec sed -i 's@image: .*@image: '"${{ env.IMAGE_NAME }}:${{ steps.extract_version.outputs.VERSION }}"'@' {} \;
        cat ./deploy/deployment.yaml

    - name: Commit changes
      run: |
        git config --local user.email "yjring@gmail.com"
        git config --local user.name "DannyYang"
        git add ./deploy/*.yaml
        git commit -m "Update image version to ${{ steps.extract_version.outputs.VERSION }}" -a
        git push origin main
